### PR TITLE
Improve connection issue handling

### LINKED ISSUE #2: Connection isn't restored after timeout
Sometimes the connection to the gotify server times out, causing the indicator to disconnect and not reconnect, resulting in no notifications.

From the console output:

```
[Errno 110] Connection timed out
[...]
### closed ###
```

Manually stopping and restarting the service restores notifications until the next timeout.

### PR DESCRIPTION
**Pull request by newhinton**
fixes #2 
After the connection times out, during hibernate or otherwise, the thread does not restart the websocket. This pr runs a loop that checks every minute if it is still connected, and restarts if not.

It also displays a new red icon when an error has occured. The tray now also acts as passive(APP_INDICATOR_STATUS_PASSIVE), and hides itself when working properly (as operating systems support this feature). Only when an error has occured it makes itself important so that the OS can properly display it (APP_INDICATOR_STATUS_ATTENTION)

### CODE REVIEW

**Comment by tatokis** [comment]
While testing this PR, I noticed that since the tray icon is now passive/hidden by default, there is no way to configure the application. Running it again just says `application already running` and exits.

**Comment by newhinton** [comment]
@tatokis Which distribution are you using? I am using KDE which provides the ability to show a notification "only when relevant". As per documentation those states exist:

grafik

I assumed that "passive" is a more appropriate state, since that moves it to the overhang menu. Does your system has such an menu?

**Comment by tatokis** [comment]
I'm running Unity on Ubuntu 20.04.
There is no overhang menu, so the icon just completely disappears. The indicator is in fact "not shown to the user" in my case.

It also looks like it's trying to play back a notification sound but fails, as one doesn't exist. There doesn't seem to be one set, but I personally don't really want sounds, so it works out.
It does spit this out in the console though for every notification, which is not ideal. Maybe it should be considered that the sound notifications are off if the key doesn't exist, or isn't empty. I haven't gone through the code to see how it's implemented.

```
error from callback <bound method Indicator.on_message of <indicator.Indicator object at 0x7f329efbafd0>>: 'notification_sound'
  File "/opt/extras.ubuntu.com/gotify-indicator/share/gotify-indicator/websocket/_app.py", line 344, in _callback
    callback(*args)
  File "/opt/extras.ubuntu.com/gotify-indicator/share/gotify-indicator/indicator.py", line 295, in on_message
    play(self.getNotificationSound())
  File "/opt/extras.ubuntu.com/gotify-indicator/share/gotify-indicator/indicator.py", line 301, in getNotificationSound
    custom_path = preferences['notification_sound']
```

**Comment by newhinton** [comment]
The missing notification sound is working as intended. The exception beeing thrown everytime is not, i'll fix that.

I will see how to handle the notification icon with ubuntu, but it may take a while.

Do you need help modifying my code so that you can run it until i fix it properly?

**Comment by tatokis** [comment]
> Do you need help modifying my code so that you can run it until i fix it properly?

Apologies for the late reply, but no need. Appreciate it though!

**Pull request merged**
